spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

weather:
  api:
    service-key: gQxQDUh9cjv0vgEqDuZ43i7LmXIPvTkPIY47K0gehzsh3eVCiMbQyIVhCDH4kAQPvEz4aG6axSg/Ld8U1xhDaA==
